### ISSUE TITLE
lytixd crash after forked chain

### ISSUE THREAD

**Issue by faetos** [LytixChain/lytix#11]
ERROR: ContextualCheckBlockHeader: forked chain older than max reorganization depth (height 7941)
Segmentation fault (core dumped)
#0  0x000056126de747c3 in ProcessNewBlock (state=..., pfrom=0x56127c901000, pblock=0x7fce411c68c0, dbp=0x0) at main.cpp:4550
        nodestate = 0x56128326a8a8
        nodeStatus = <optimized out>
        nDoS = <optimized out>
        criticalblock51 = {lock = {m = 0x56126e390b80 <cs_main>, is_locked = true}}
        pindex = 0x0
        ret = false
        nStartTime = 1551079710278
        checked = true
        nMints = 0
        nSpends = 0
        __func__ = "ProcessNewBlock"
#0  0x000056126de747c3 in ProcessNewBlock (state=..., pfrom=0x56127c901000, pblock=0x7fce411c68c0, dbp=0x0) at main.cpp:4550
4550                    nodestate->nodeBlocks.onBlockReceived(pindex->nHeight);

  

      // Store to disk
        CBlockIndex* pindex = nullptr;
        bool ret = AcceptBlock (*pblock, state, &pindex, dbp, checked);

then later on 
            // Check spamming
            if(pfrom && GetBoolArg("-blockspamfilter", DEFAULT_BLOCK_SPAM_FILTER)) {
                CNodeState *nodestate = State(pfrom->GetId());
                nodestate->nodeBlocks.onBlockReceived(pindex->nHeight);
doesn't actually check if AcceptBlock fails

**Comment by faetos** [comment]
fixed in PR https://github.com/LytixChain/lytix/commit/3858a793b777c81bf7a6c8f9fb5d5f7341133b48
